name: Bike Rental Prediction CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  train_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Create virtual environment
        run: python -m venv .venv
      
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
          
      - name: Train model
        run: |
          source .venv/bin/activate
          python train_pipeline.py
          
      - name: Run prediction
        run: |
          source .venv/bin/activate
          python predict.py
          
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
          
      - name: Build package
        run: |
          source .venv/bin/activate
          pip install build
          python -m build
          
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel-file
          path: dist/*.whl
          
  build_and_push_docker:
    needs: train_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download wheel artifact
        uses: actions/download-artifact@v2
        with:
          name: wheel-file
          path: bikeshare_model_api
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./bikeshare_model_api
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bikeshare-api:latest
            ${{ secrets.DOCKER_USERNAME }}/bikeshare-api:v${{ github.run_number }}